version: "{build}"

branches:
  only:
    - master
    - code_climate_repo_token

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler
  - bundler --version
  - bundle install

build_script:
  - bundle exec rake native

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: '200'
    - ruby_version: '200-x64'
    - ruby_version: '21'
    - ruby_version: '21-x64'

  codeclimate_repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
